login screen tested
bluntbrain/fit-manager pull request #1
Opened 2023-10-24 10:30 UTC by bluntbrain

2023-10-25 05:23 UTC, atulpatel-03 commented on App.tsx
>  function App(): JSX.Element {
All new components will be functional components

2023-10-25 05:25 UTC, atulpatel-03 commented on src/components/common/Button.tsx
> +import colors from '../../theme/colors';
Library imports on top, a space and then rest imports

2023-10-25 05:25 UTC, atulpatel-03 commented on src/components/common/Button.tsx
> +const Button = ({title, onPress, disabled = false}) => {
For Props, Please define its TS Type

2023-10-25 05:27 UTC, atulpatel-03 commented on src/components/common/Button.tsx
> +  const [is_loading, set_is_loading] = useState(false);
For ever useState, define its TS type ...Like useState<boolean>

2023-10-25 05:28 UTC, atulpatel-03 commented on src/screens/UserOnboardingAndAuth/Login.tsx
> +  console.log('confirm', confirm);
remove console.log  while pushing the code

2023-10-25 05:29 UTC, atulpatel-03 commented on src/screens/UserOnboardingAndAuth/components/OTPVerification.tsx
> +import {AuthContext} from '../context';
Library imports on top, a space and then rest imports

2023-10-25 05:30 UTC, atulpatel-03 commented on src/screens/UserOnboardingAndAuth/useOnboardingAndAuth.tsx
> +  const [code, set_code] = useState('');
Define TS type for all the states

2023-10-25 05:30 UTC, atulpatel-03 commented on src/screens/UserOnboardingAndAuth/useOnboardingAndAuth.tsx
> +      console.log('Confirmed!');
Remove console.log

2023-10-25 05:31 UTC, atulpatel-03 commented on src/screens/UserOnboardingAndAuth/useOnboardingAndAuth.tsx
> +      console.log('Invalid code.');
Remove here also

2023-10-25 06:36 UTC, atulpatel-03 commented on src/components/common/Button.tsx
> +interface ButtonProps {
Only Give Props as name

2024-01-02 06:36 UTC, bluntbrain commented on src/components/common/Button.tsx
> +interface ButtonProps {
discussed

2024-01-02 07:41 UTC, shreyanshgoel9 requested changes

2024-01-02 07:41 UTC, shreyanshgoel9 commented on src/screens/UserOnboardingAndAuth/useOnboardingAndAuth.tsx
> +  async function confirm_code() {
arrow functions only

2024-01-02 07:41 UTC, shreyanshgoel9 commented on src/screens/UserOnboardingAndAuth/useOnboardingAndAuth.tsx
> +  }
give space after functions

2024-01-02 07:41 UTC, shreyanshgoel9 commented on src/screens/UserOnboardingAndAuth/useOnboardingAndAuth.tsx
> +export const useOnboardingAndAuth = () => {
use export default when exporting the main function

2024-01-02 07:41 UTC, shreyanshgoel9 commented on src/screens/UserOnboardingAndAuth/components/PhoneNumberInput.tsx
> +    <View style={styles.container}>
seems like eslint is not setup, please see to it that its setup

2024-01-02 08:45 UTC, bluntbrain commented on src/screens/UserOnboardingAndAuth/useOnboardingAndAuth.tsx
> +  async function confirm_code() {
resolved

2024-01-02 08:46 UTC, bluntbrain commented on src/screens/UserOnboardingAndAuth/useOnboardingAndAuth.tsx
> +  }
resolved

2024-01-02 08:49 UTC, bluntbrain commented on src/screens/UserOnboardingAndAuth/components/PhoneNumberInput.tsx
> +    <View style={styles.container}>
resolved

2024-01-02 08:49 UTC, bluntbrain commented on src/screens/UserOnboardingAndAuth/useOnboardingAndAuth.tsx
> +export const useOnboardingAndAuth = () => {
resolved

2024-01-02 09:06 UTC, merged