feat: Registration
bluntbrain/fit-manager pull request #2
Opened 2023-11-20 02:48 UTC by bluntbrain

2023-11-20 04:51 UTC, atulpatel-03 commented on src/screens/UserOnboardingAndAuth/Registration.tsx
> +  React.useEffect(() => {
import useEffect above than use it

2023-11-20 04:53 UTC, atulpatel-03 commented on src/screens/UserOnboardingAndAuth/useOnboardingAndAuth.tsx
>    async function sign_in_with_phone_number() {
use arrow functions

2024-01-02 06:51 UTC, bluntbrain commented on src/screens/UserOnboardingAndAuth/Registration.tsx
> +  React.useEffect(() => {
resolved

2024-01-02 06:53 UTC, bluntbrain commented on src/screens/UserOnboardingAndAuth/useOnboardingAndAuth.tsx
>    async function sign_in_with_phone_number() {
resolved

2024-01-02 06:56 UTC, bluntbrain commented on src/screens/UserOnboardingAndAuth/useOnboardingAndAuth.tsx
>    async function confirm_code() {
resolved

2024-01-02 07:42 UTC, shreyanshgoel9 requested changes

2024-01-02 07:42 UTC, shreyanshgoel9 commented on src/screens/UserOnboardingAndAuth/Registration.tsx
> +      {errors.owner_name && (
use isEmpty otherwise in case of undefined it will print false and break the code

2024-01-02 09:16 UTC, bluntbrain commented on src/screens/UserOnboardingAndAuth/Registration.tsx
> +      {errors.owner_name && (
resolved

2024-01-02 09:18 UTC, merged